### ISSUE TITLE
Support for SRAI and SRLI

### ISSUE THREAD

**Issue by sayma10** [quentin-meunier/LeakageVerif#1]
I have a question regarding the framework support for arithmetic and logical operators , particularly SRAI and SRLI.
    def __rshift__(self, shval):
        # Arith Shift Right
        if isinstance(shval, ConstNode):
            shval = shval.cst
        if not isinstance(shval, int):
            print('*** Error: Second operand of a Shift operation can only be a constant')
            assert(False)

        width = self.width
        if shval >= width:
            print('*** Warning: shift value (%d) >= bit width of expression (%d)' % (shval, width))

        if propagateCstOnBuild() and isinstance(self, ConstNode):
            cst = self.cst
            if cst >> (width - 1) == 1: # MSB == 1
               mod = 1 << width
               n = Const(~((~cst % mod) >> shval) % mod, width)
            else:
               n = Const(cst >> shval, width)
            return n

        sh = Const(shval, shval.bit_length())
        n = OpNode('>>', [self, sh])
        return n
In Node file, why is SRAI only for constant nodes and not for any other public node or Opnode.

**Comment by quentin-meunier** [comment]
Hi,

for all the shifts, the shift amount must indeed be an integer and not a symbolic expression, meaning that you can write:
```
a = symbol('a', 'M', 8)
e = a >> 4
```
but you cannot write:
```
a = symbol('a', 'M', 8)
b = symbol('b', 'M', 8)
e = a >> b
```
This is because the latter has not much utility in practice and cannot be processed/simplified properly.

Besides, I suggest you switch from LeakageVerif to VerifMSI, as the latter is an extension of LeakageVerif with more functionalities, and which also fixes a few things (I keep this repository as a reference for the TSE article).
