### ISSUE TITLE
Change of Masks in Mix Columns Operation

### ISSUE THREAD

**Issue by sayma10** [quentin-meunier/LeakageVerif#2]
Dear Sir,

Thankyou for the explanation for SRLI and SRAI.

However i have one doubt, how come mix columns operations changes masks.

I was going through your aes-herbst-orig.py code.

I understand we need to update mask with precomputing mix columns operation done by this 
def mix_column(r):
    a = {}
    b = {}
    for c in range(4):
        a[c] = r[c]
        h = r[c] >> 7 # 8 bits
        b[c] = r[c] << 1
        b[c] ^= constant(0x1b, 8) & h
    r[0] = b[0] ^ a[3] ^ a[2] ^ b[1] ^ a[1]
    r[1] = b[1] ^ a[0] ^ a[3] ^ b[2] ^ a[2]
    r[2] = b[2] ^ a[1] ^ a[0] ^ b[3] ^ a[3]
    r[3] = b[3] ^ a[2] ^ a[1] ^ b[0] ^ a[0]

after this, we will get the updated value of last four masks out of which i m just mentioning value of m1' as below.
{OpNode}0xff & ( mask_1^
(((((((((((((0x1b & (mask_0 >> 7)) << 24) >> 24) ^
((((mask_0 << 1) & 0xff) << 24) >> 24)) << 24) >> 24)
& 0xff) ^ mask_3) & 0xff) ^ mask_2) & 0xff) ^
(((((((0xff & (mask_1 << 1)) << 24) >> 24) ^
((((mask_1 >> 7) & 0x1b) << 24) >> 24)) << 24) >> 24)
& 0xff)) & 0xff))

However, during round loop Mix Columns operation def mix_columns(x):
    def xtime(y):
        return (y << 1) ^ ((y >> 7) & constant(0x1b, 8))

    for i in range(4):
        t        = x[0][i]
        tmp      = x[0][i] ^ x[1][i] ^ x[2][i] ^ x[3][i]
        tm       = x[0][i] ^ x[1][i]
        tm       = xtime(tm)
        x[0][i] ^= tm ^ tmp
        tm       = x[1][i] ^ x[2][i]
        tm       = xtime(tm)
        x[1][i] ^= tm ^ tmp
        tm       = x[2][i] ^ x[3][i]
        tm       = xtime(tm)
        x[2][i] ^= tm ^ tmp
        tm       = x[3][i] ^ t
        tm       = xtime(tm)
        x[3][i] ^= tm ^ tmp

Again masks would be updated from m1 to m1'. m2 to m2' etc.
If i just take masks value for state [0][0] update
    for i in range(4):
        t        = This would be having m1
        tmp      = this would be with mask m1^m2^m3^m4
        tm       = This would be again m1^m2
        tm       = xtime(tm)----some shifting
        x[0][0] =x[0][0]^ tm ^ tmp which would be with mask (m1^m1^m2^m3^m4^m1^m2)..
hence only mask m1, m3 and m4 would remain ...but if i see the value of mask update for m1' it is coming different as it has all four masks in it

really confused . could you help me in this

**Comment by quentin-meunier** [comment]
Hi,

I am not sure to understand what the problem is. The two versions of the mix_columns are equivalent. In fact, the `xtime` function in `mix_columns` does the multiplication by 2, the same way as the lines:
```
h = r[c] >> 7 # 8 bits
b[c] = r[c] << 1
b[c] ^= constant(0x1b, 8) & h
```
in the `mix_column` function.
Without considering masks, in both functions, for an input column (a0, a1, a2, a3), the output column is :
(2 * a0 + 3 * a1 + a2 + a3, a0 + 2 * a1 + 3 * a2 + a3, a0 + a1 + 2 * a2 + 3 * a3, 3 * a0 + a1 + a2 + 2 * a3)
This is in particular the case for the x[0][0] that you mention, since we have :
```
x[0][0] = x[0][0] ^ 2 * (x[0][0] ^ x[1][0]) ^ x[0][0] ^ x[1][0] ^ x[2][0] ^ x[3][0]
       = 2 * x[0][0] ^ 2 * x[1][0] ^ x[1][0] ^ x[2][0] ^ x[3][0]
       = 2 * x[0][0] ^ 3 * x[1][0] ^ x[2][0] ^ x[3][0]
```
As the computation is the same as in the first version, the mask change is exactly the same as well. Maybe your confusion comes from the fact that you forgot that the xtime ("some shifting") is not the identity, and thus masks do not cancel?

Best Regards,
Quentin

**Comment by sayma10** [comment]
Thankyou so much Mr Quentin for clearling my doubt :)

**Comment by quentin-meunier** [comment]
No problem, you are welcome.
